# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/agent-search',
                'doc_host': 'https://tongyx361.github.io',
                'git_url': 'https://github.com/tongyx361/agent-search',
                'lib_path': 'agent_search'},
  'syms': {'agent_search.core': {'agent_search.core.foo': ('core.html#foo', 'agent_search/core.py')}}}
